version: '3.1' 
services:
    qbittorrent:
        image: linuxserver/qbittorrent
        container_name: qbittorrent
        restart: always
        network_mode: host
        ports:
            - '8080:8080'
        volumes:
            - '/vol1/1000/Dockers/qbittorrent:/config'
            - '/vol1/1000/Dockers/qbittorrent:/downloads'
            - '/vol1/1000/Dockers/qbittorrent:/downloads_m'
        environment:
            - 'PUID=1000'
            - 'PGID=1000'
            - 'TZ=Asia/Shanghai'
